# Generated by Django 3.1.7 on 2021-04-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('middlename', models.CharField(max_length=130)),
                ('surname', models.CharField(max_length=130)),
                ('dob', models.DateField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='pictures/')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
