# Generated by Django 3.1.7 on 2021-04-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210409_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='dob',
            field=models.DateTimeField(max_length=130),
        ),
    ]
