# Generated by Django 3.1.7 on 2021-04-09 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210409_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
