# Generated by Django 3.1.7 on 2021-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210409_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image1',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
    ]
